### ISSUE TITLE
HOW TO RUN THIS

### ISSUE THREAD

**Issue by animeworld0310** [mrmelon54/WhatsAppExportViewer#1]
Please make a video tutorial on how to run this project 

As you made this project and you are familiar with it so you will require very less time to make a tutorial and explain it 
this is my humble request

**Comment by mrmelon54** [comment]
You probably want to download the [latest release](https://github.com/MrMelon54/WhatsAppExportViewer/releases/latest)

I added that information to the readme as well

**Comment by animeworld0310** [comment]
> You probably want to download the [latest release](https://github.com/MrMelon54/WhatsAppExportViewer/releases/latest)
> 
> I added that information to the readme as well

I want to talk with you for a new project idea can give your email or telegram I'd?

**Comment by mrmelon54** [comment]
I have an email address on my github profile

edit: I'm gonna assume the other email I received was you

**Comment by animeworld0310** [comment]
> I have an email address on my github profile

I have mailed you on that email please do check 😊

Edit: Yes it is me
