### ISSUE TITLE
Getting an error while opening a whatsapp txt backup

### ISSUE THREAD

**Issue by salim0786** [mrmelon54/WhatsAppExportViewer#2]
Getting this error:
It seems that your log file was unable to be read.

This is probably due to it not being exported from WhatsApp or due to the date/time format not being recognised by this software.

Note- The backup was a txt file from whatsapp but was from an Android device. It is working fine on iOS

**Comment by mrmelon54** [comment]
Can you open the txt file and send me a copy of the date so I can update this program to read it correctly

**Comment by salim0786** [comment]
Hi,
This is a portion of the text,
6/13/23, 7:35 PM - Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.
6/13/23, 7:35 PM - Salim Khan: Hi, asalamualaikum
6/13/23, 7:36 PM - Sadika: Waalaikum assalam
6/13/23, 7:36 PM - Sadika: Is it your no?
6/13/23, 7:36 PM - Salim Khan: Yes
6/13/23, 7:36 PM - Sadika: Or handling by your parents?
6/13/23, 7:36 PM - Sadika: Okok
6/13/23, 7:36 PM - Sadika: Kidding
6/13/23, 7:37 PM - Salim Khan: I need some details.
Your full name please as well as your date of birth...

**Comment by mrmelon54** [comment]
Ok apparently one of those "spaces" is a non-space character

**Comment by mrmelon54** [comment]
Fixed with latest update

**Comment by Kilsven** [comment]
Thanks for this software. I have the same issue as salim0786.
Can it be due to the way the date/time format?

It's an export from an Android device.

Example:
03-12-2023 12:34 - [name]: message
03-12-2023 12:34 - [name]: message
03-12-2023 12:34 - [name]: ‎VID-20231203-WA0014.mp4 (bestand bijgevoegd)
03-12-2023 12:34 - [name]: message

Thanks!
