### ISSUE TITLE
"It seems that your log file was unable to be read."

### ISSUE THREAD

**Issue by Kilsven** [mrmelon54/WhatsAppExportViewer#4]
Thanks for this software.
I have the same issue as salim0786. The software states:
"It seems that your log file was unable to be read.  This is probably due to it not being exported from WhatsApp or due to the date/time format not being recognised by this software."

I get an error message when trying to import a chat. Can it be due to the format of the date/time?
It's an export from an Android device.

Example:
03-12-2023 12:34 - [name]: ‎VID-20231203-WA0012.mp4
03-12-2023 12:34 - [name]: ‎VID-20231203-WA0013.mp4 (bestand bijgevoegd)
03-12-2023 12:34 - [name]: ‎VID-20231203-WA0014.mp4 (bestand bijgevoegd)
03-12-2023 12:34 - [name]: <Media weggelaten>

Thanks!

**Comment by mrmelon54** [comment]
Resolved in v2.0.6
